jqassistant:
  plugins:
    - group-id: de.kontext-e.jqassistant.plugin
      artifact-id: jqassistant.plugin.git
      version: 2.2.2
  scan:
    include:
      files:
    properties:
      #Example for properties
      json.file.include: '*.json'
  analyze:
    rule:
      directory: './rules'
    groups:
      #Don't worry about the concept application failure,
      #This is purely for demonstration purposes
      - '*'
    rule-parameters:
    # Parameter: 123
    execute-applied-concepts: true
  repositories:
    remotes:
      #Snapshot only necessary when using snapshot dependencies
      snapshot:
        url: https://oss.sonatype.org/content/repositories/snapshots
  store:
    embedded:
      neo4j-plugins:
        - group-id: org.neo4j.procedure
          artifact-id: apoc-core
          classifier: core
          version: 5.24.1